### 결의서 등록
POST http://localhost:8888/expenditure/resolution/save
Content-Type: application/json

{
  "resolutionId": "",
  "resolutionDate": "",
  "resolutionNumber": "",
  "applicant": "90001",
  "applicationDepartment": "D50001",
  "applicationAmount": "60000000",
  "summary": "지출결의 신청",
  "applicationCategory": "01",
  "electronicPaymentNumber": "",
  "resolutionDetailVO": [
    {
      "resolutionDate": "20210225",
      "resolutionNumber": "00001",
      "resolutionTurn": "1",
      "user": "90002",
      "accNumber": "SR001",
      "costCode": "B002",
      "budgetYear": "2021",
      "annualNumber": "1",
      "receipt": "01",
      "executionAmount": "60000000",
      "cardNumber": "9100100020030002",
      "approvalNumber": "00000014",
      "cardCompany": "국민은행",
      "bank": "",
      "accountHolder": "",
      "accountNumber": "",
      "customerName": "",
      "causeActionNumber": "",
      "resolutionAttachmentVO": [
        {
          "resolutionDate": "",
          "resolutionNumber": "",
          "resolutionTurn": "",
          "attachmentCategory": "",
          "attachmentId": ""
        }
      ]
    },

    {
      "resolutionDate": "20210225",
      "resolutionNumber": "00001",
      "resolutionTurn": "2",
      "user": "90002",
      "accNumber": "SR001",
      "costCode": "B002",
      "budgetYear": "2021",
      "annualNumber": "1",
      "receipt": "01",
      "executionAmount": "60000000",
      "cardNumber": "9100100020030002",
      "approvalNumber": "00000014",
      "cardCompany": "국민은행",
      "bank": "",
      "accountHolder": "",
      "accountNumber": "",
      "customerName": "",
      "causeActionNumber": "",
      "resolutionAttachmentVO": [
        {
          "resolutionDate": "",
          "resolutionNumber": "",
          "resolutionTurn": "",
          "attachmentCategory": "",
          "attachmentId": ""
        }
      ]
    }
  ]
}


### 결의서 수정
POST http://localhost:8888/expenditure/resolution/save
Content-Type: application/json

{
  "resolutionId": "202132000001",
  "resolutionDate": "202132",
  "resolutionNumber": "000001",
  "applicant": "90001",
  "applicationDepartment": "D50001",
  "applicationAmount": "60000000",
  "summary": "지출결의 신청",
  "applicationCategory": "01",
  "electronicPaymentNumber": "",
  "resolutionDetailVO": [
    {
      "resolutionDate": "20210225",
      "resolutionNumber": "00001",
      "resolutionTurn": "1",
      "user": "90002",
      "accNumber": "SR001",
      "costCode": "B002",
      "budgetYear": "2021",
      "annualNumber": "1",
      "receipt": "01",
      "executionAmount": "60000000",
      "cardNumber": "9100100020030002",
      "approvalNumber": "00000014",
      "cardCompany": "국민은행",
      "bank": "",
      "accountHolder": "",
      "accountNumber": "",
      "customerName": "",
      "causeActionNumber": "",
      "resolutionAttachmentVO": [
        {
          "resolutionDate": "",
          "resolutionNumber": "",
          "resolutionTurn": "",
          "attachmentCategory": "",
          "attachmentId": ""
        }
      ]
    },

    {
      "resolutionDate": "20210225",
      "resolutionNumber": "00001",
      "resolutionTurn": "2",
      "user": "90002",
      "accNumber": "SR001",
      "costCode": "B002",
      "budgetYear": "2021",
      "annualNumber": "1",
      "receipt": "01",
      "executionAmount": "60000000",
      "cardNumber": "9100100020030002",
      "approvalNumber": "00000014",
      "cardCompany": "국민은행",
      "bank": "",
      "accountHolder": "",
      "accountNumber": "",
      "customerName": "",
      "causeActionNumber": "",
      "resolutionAttachmentVO": [
        {
          "resolutionDate": "",
          "resolutionNumber": "",
          "resolutionTurn": "",
          "attachmentCategory": "",
          "attachmentId": ""
        }
      ]
    }
  ]
}
