###
POST http://localhost:8888/expenditure/resolution/tracking
Content-Type: application/json

{
  "trackingEventProcessorName": "com.ibdata.eventsourcing.acc.resolution.projection",
  "index": 1382
}